id: 395eae9937e54b128072dd145f181463
initial_creation_type: ocr
source_metadata:
  volumes:
    fafc839ecb074e8fada2cf7ac625c531:
      base_file: v063.txt
      image_group_id: I1PD95909
      title: ''
      total_pages: 1902
      volume_number: 64
